pipeline:
  agent:
    any

  stages:
    - stage: Build
      steps:
        - script:
            displayName: "Build Project"
            script: |
              echo 'Building backend Connection established with Docker on port 9000...'
              git 'https://github.com/binitworld/AB'
              sh 'npm install'
              sh 'npm run build'

    - stage: Test
      steps:
        - script:
            displayName: "Run Tests"
            script: |
              echo 'Running Tests...'
              # Replace 'bpm test' with the actual command to run your tests
              sh 'bpm test'

    - stage: Deploy
      steps:
        - script:
            displayName: "Deploy to Server"
            script: |
              echo 'Deploying to Server...'
              # Add your deployment commands here
