pipeline:
  agent:
    any

  stages:
    - stage: "Build"
      steps:
        - script:
            name: "Clone Repository"
            script: |
              echo 'Cloning repository...'
              git 'https://github.com/binitworld/Shop-Sphere'
        - script:
            name: "Build HTML, CSS, JavaScript"
            script: |
              echo 'Building HTML, CSS, JavaScript...'
              sh 'npm install'
              sh 'npm run build'

    - stage: "Test"
      steps:
        - script:
            name: "Run Tests"
            script: |
              echo 'Running Tests...'
              # Add commands to run your tests here
              bpm test

    - stage: "Deploy"
      steps:
        - script:
            name: "Deploy to Server"
            script: |
              echo 'Deploying to Server...'
              # Add deployment commands here

  post:
    always:
      - script:
          name: "Cleanup"
          script: |
            echo 'Performing Cleanup...'
            sh 'npm clean'
